# S&P 500 2-State Student-t HMM Configuration - STABLE REGIMES V2
# More aggressive smoothing for ~10 day average regime duration

data:
  symbol: "^GSPC"
  start_date: "2000-01-01"
  end_date: "2024-01-01"
  cache_dir: "./data/raw"
  
features:
  returns_column: "returns"
  rolling_window: 100  # Much larger window (was 20, then 50, now 100)
  volatility_column: "rolling_std"
  volatility_method: "ewm"  # Use exponentially weighted moving average
  additional_features:
    - "abs_returns"
    # Remove negative_returns and z_score_returns as they might be too noisy
    
model:
  name: "student_t_hmm"
  n_states: 2
  emission_type: "student_t"
  diagonal_covariance: true
  
training:
  algorithm: "baum_welch"
  max_iterations: 100
  tolerance: 0.000001
  random_seed: 42
  
output:
  artifacts_dir: "./artifacts_stable_v2"
  reports_dir: "./reports_stable_v2"
  figures_dir: "./reports_stable_v2/figures"
  
logging:
  level: "INFO"
  file: "./logs/regime_lab_stable_v2.log"

