# S&P 500 2-State Student-t HMM Configuration - STABLE REGIMES
# Designed to produce ~10 day average regime duration

data:
  symbol: "^GSPC"
  start_date: "2000-01-01"
  end_date: "2024-01-01"
  cache_dir: "./data/raw"
  
features:
  returns_column: "returns"
  rolling_window: 50  # Increased from 20 to 50 for smoother volatility
  volatility_column: "rolling_std"
  volatility_method: "ewm"  # Use exponentially weighted moving average for smoothness
  additional_features:
    - "abs_returns"
    - "negative_returns"
    - "z_score_returns"

model:
  name: "student_t_hmm"
  n_states: 2
  emission_type: "student_t"
  diagonal_covariance: true
  # HMM will learn transition probabilities, but with smoother features
  # it should naturally find more persistent regimes
  
training:
  algorithm: "baum_welch"
  max_iterations: 100
  tolerance: 0.000001
  random_seed: 42
  
output:
  artifacts_dir: "./artifacts_stable"
  reports_dir: "./reports_stable"
  figures_dir: "./reports_stable/figures"
  
logging:
  level: "INFO"
  file: "./logs/regime_lab_stable.log"

